"""create author table

Revision ID: 2f1a327c3688
Revises: 1f50fbae4c1e
Create Date: 2026-05-04 20:50:52.919496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f1a327c3688'
down_revision: Union[str, Sequence[str], None] = '1f50fbae4c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('role', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'role')
    # ### end Alembic commands ###
