"""add user fields

Revision ID: 7e88a976f72e
Revises: b35b6779de91
Create Date: 2026-04-17 16:11:27.955499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e88a976f72e'
down_revision: Union[str, Sequence[str], None] = 'b35b6779de91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('author', sa.Column('gender', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'gender')
    op.drop_column('author', 'phone_number')
    # ### end Alembic commands ###
