"""create author table

Revision ID: d07290fca7a8
Revises: cc8e9036c54a
Create Date: 2026-05-03 20:01:46.895394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd07290fca7a8'
down_revision: Union[str, Sequence[str], None] = 'cc8e9036c54a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('user_avatar', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'user_avatar')
    # ### end Alembic commands ###
